name: HyperCosmetics
authors: ["Sammwy", "LinsaFTW"]
main: "dev._2lstudios.hypercosmetics.HyperCosmetics"
version: 0.0.1
api: "legacy"
commands:
    hypercosmetics:
        description: "Main command for cosmetics"
        aliases: ["hc", "hyperc"]
    cosmetics:
        description: "Open cosmetics GUI"
        aliases: ["cgui", "cg"]