name: ${name}
description: ${description}
author: ${author}
main: ${mainClass}
version: ${version}
url: ${url}
commands:
    cosmetics:
        description: "Main command for cosmetics"
        aliases: [ "hypercosmetics" ]